// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/go-orb/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/go-orb/go-orb/cli"
	"github.com/go-orb/go-orb/client"
	"github.com/go-orb/go-orb/log"
	"github.com/go-orb/go-orb/registry"
	"github.com/go-orb/go-orb/types"
	"github.com/go-orb/plugins/cli/urfave"
)

import (
	_ "github.com/go-orb/plugins/client/middleware/log"
	_ "github.com/go-orb/plugins/client/orb"
	_ "github.com/go-orb/plugins/client/orb_transport/drpc"
	_ "github.com/go-orb/plugins/codecs/json"
	_ "github.com/go-orb/plugins/codecs/proto"
	_ "github.com/go-orb/plugins/codecs/yaml"
	_ "github.com/go-orb/plugins/config/source/file"
	_ "github.com/go-orb/plugins/log/slog"
	_ "github.com/go-orb/plugins/registry/consul"
	_ "github.com/go-orb/plugins/registry/mdns"
)

// Injectors from wire.go:

func run(appContext *cli.AppContext, args []string, cb wireRunCallback) (wireRunResult, error) {
	serviceContext, err := cli.ProvideSingleServiceContext(appContext)
	if err != nil {
		return "", err
	}
	appConfigData, err := cli.ProvideAppConfigData(appContext)
	if err != nil {
		return "", err
	}
	parserFunc, err := urfave.ProvideParser()
	if err != nil {
		return "", err
	}
	v, err := cli.ProvideParsedFlagsFromArgs(appContext, parserFunc, args)
	if err != nil {
		return "", err
	}
	serviceContextWithConfig, err := cli.ProvideServiceConfigData(serviceContext, appConfigData, v)
	if err != nil {
		return "", err
	}
	v2, err := types.ProvideComponents()
	if err != nil {
		return "", err
	}
	logger, err := log.ProvideNoOpts(serviceContextWithConfig, v2)
	if err != nil {
		return "", err
	}
	registryType, err := registry.ProvideNoOpts(serviceContextWithConfig, v2, logger)
	if err != nil {
		return "", err
	}
	clientType, err := client.ProvideNoOpts(serviceContextWithConfig, v2, logger, registryType)
	if err != nil {
		return "", err
	}
	mainWireRunResult, err := wireRun(serviceContext, logger, clientType, v2, cb)
	if err != nil {
		return "", err
	}
	return mainWireRunResult, nil
}

// wire.go:

// wireRunResult is here so "wire" has a type for the return value of wireRun.
// wire needs a explicit type for each provider including "wireRun".
type wireRunResult string

// wireRunCallback is the actual code that runs the business logic.
type wireRunCallback func(
	serviceContext *cli.ServiceContext,
	logger log.Logger, client2 client.Type,

) error

func wireRun(
	serviceContext *cli.ServiceContext,
	logger log.Logger, client2 client.Type,

	components *types.Components,
	cb wireRunCallback,
) (wireRunResult, error) {

	for _, c := range components.Iterate(false) {
		err := c.Start(serviceContext.Context())
		if err != nil {
			logger.Error("Failed to start", "error", err, "component", fmt.Sprintf("%s/%s", c.Type(), c.String()))
			return "", err
		}
	}

	runErr := cb(serviceContext, logger, client2)

	ctx := context.Background()

	for _, c := range components.Iterate(true) {
		err := c.Stop(ctx)
		if err != nil {
			logger.Error("Failed to stop", "error", err, "component", fmt.Sprintf("%s/%s", c.Type(), c.String()))
		}
	}

	return "", runErr
}
