version: "3"

tasks:
  lint:
    desc: Run "golangci-lint" in all packages
    cmds:
      - cmd: dagger call lint --root=.

  mod-tidy:
    desc: Run "go mod tidy" in all packages
    cmds:
      - cmd: dagger call tidy --root=. source export --path=.

  mod-update:
    desc: Run "go get -u -t ./..." in all packages
    cmds:
      - cmd: dagger call update --root=. source export --path=.

  test:
    desc: Run "go test ./..." in all packages and then "./scripts/test.sh" to test all binaries.
    cmds:
      - cmd: dagger call test --root=.
      - cmd: ./scripts/test.sh

  generate:
    desc: "Run go generate ./... in all packages."
    cmds:
    - |
      for i in $(find . -type d); do 
        [[ ! -f $i/go.mod ]] && continue
        pushd $i 1>/dev/null
        echo $i
        go generate ./... || true
        popd 1>/dev/null
      done