// Code generated by protoc-gen-go-orb. DO NOT EDIT.
//
// version:
// - protoc-gen-go-orb        v0.0.1
// - protoc                   v5.29.2
//
// source: lobby_v1/lobby_v1.proto

package lobby_v1

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_lobby_v1_lobby_v1_proto struct{}

func (drpcEncoding_File_lobby_v1_lobby_v1_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_lobby_v1_lobby_v1_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_lobby_v1_lobby_v1_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_lobby_v1_lobby_v1_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_lobby_v1_lobby_v1_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCLobbyServiceServer interface {
	ListGames(context.Context, *emptypb.Empty) (*ListGamesResponse, error)
}

type DRPCLobbyServiceUnimplementedServer struct{}

func (s *DRPCLobbyServiceUnimplementedServer) ListGames(context.Context, *emptypb.Empty) (*ListGamesResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCLobbyServiceDescription struct{}

func (DRPCLobbyServiceDescription) NumMethods() int { return 1 }

func (DRPCLobbyServiceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/lobby.v1.LobbyService/ListGames", drpcEncoding_File_lobby_v1_lobby_v1_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCLobbyServiceServer).
					ListGames(
						ctx,
						in1.(*emptypb.Empty),
					)
			}, DRPCLobbyServiceServer.ListGames, true
	default:
		return "", nil, nil, nil, false
	}
}

type DRPCLobbyService_ListGamesStream interface {
	drpc.Stream
	SendAndClose(*ListGamesResponse) error
}

type drpcLobbyService_ListGamesStream struct {
	drpc.Stream
}

func (x *drpcLobbyService_ListGamesStream) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcLobbyService_ListGamesStream) SendAndClose(m *ListGamesResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_lobby_v1_lobby_v1_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
